name: Revenue of Glory
favicon: null
layout_spectrum: 0.037056613713502884
typography_spectrum: 0.2375978664495051
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5765438433736563
  lightness: 0.1466863879468292
  saturation: 0.4944497374817729
  rhythmicContrast: 0.049026099033653736
purpose: []
