name: Revenue of Glory
favicon: null
layout_spectrum: 0.26635
typography_spectrum: 0.87283
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1d58b'
    - '#1f191b'
    - '#7e5b3f'
    - '#d8b37f'
    - '#c29866'
  brandStrength: 0.5765438433736563
  lightness: 0.1466863879468292
  saturation: 0.4944497374817729
  rhythmicContrast: 0.049026099033653736
purpose: []
